-- Insertar datos en la tabla de valoraciones de libros
INSERT INTO VALORACIONES_LIBROS (id_usuario, id_libro, puntuacion, comentario) VALUES
    (1, 1, 5, '¡Me encantó este libro!'),
    (2, 2, 4, 'Una historia romántica muy conmovedora.'),
    (3, 3, 5, 'Un clásico de la literatura que todos deberían leer.'),
    (4, 4, 4, '¡Increíble historia! Me mantuvo en vilo hasta el final.'),
    (5, 5, 3, 'Interesante, aunque esperaba más acción.'),
    (6, 6, 5, 'Fantástico mundo creado por el autor, me transportó completamente.'),
    (7, 7, 4, 'Intrigante trama, no pude dejar de leer hasta resolver el misterio.'),
    (8, 8, 4, 'Excelente narrativa, realmente te sumerge en la historia.'),
    (9, 9, 5, 'Una obra maestra de la ciencia ficción, ¡absolutamente brillante!'),
    (10, 10, 3, 'Entretenido, pero el final fue predecible.'),
    (11, 11, 4, 'Me mantuvo enganchado, aunque algunos giros fueron un poco forzados.'),
    (12, 12, 5, 'Impactante y emotiva, una lectura que recordaré por mucho tiempo.'),
    (13, 13, 4, 'Intrigante desde la primera página, ¡no pude soltarlo!'),
    (14, 14, 5, 'Una joya literaria, cada página es una sorpresa.'),
    (15, 15, 3, 'Me gustó, pero sentí que le faltaba algo para ser excepcional.'),
    (16, 16, 5, 'Absolutamente cautivador, ¡no podía parar de leer!'),
    (17, 17, 4, 'Bien desarrollado y con un final sorprendente.'),
    (18, 18, 5, 'Me hizo reflexionar sobre la naturaleza humana, muy poderoso.'),
    (19, 19, 4, 'Misteriosa y fascinante, una lectura que te atrapa desde el inicio.'),
    (20, 20, 3, 'Interesante pero algo predecible en algunos puntos.'),
    (21, 21, 5, 'Una aventura épica que me dejó sin aliento.'),
    (22, 22, 4, 'Romántico y conmovedor, perfecto para una tarde tranquila.'),
    (23, 23, 5, 'Un clásico que nunca pasa de moda, simplemente maravilloso.'),
    (24, 24, 4, 'Inquietante y perturbador, exactamente lo que esperaba de este autor.'),
    (25, 25, 3, 'Entretenido pero un poco lento en algunas partes.'),
    (26, 26, 5, 'Fantástico y lleno de magia, una lectura que recomendaré a todos.'),
    (27, 27, 4, 'Intrigante desde el principio hasta el final, ¡lo devoré en un día!'),
    (28, 28, 4, 'Conmovedor y bien escrito, me hizo llorar más de una vez.'),
    (29, 1, 5, 'Una obra maestra del género, ¡no puedo esperar para leer más del autor!'),
    (30, 2, 3, 'Divertido pero un poco predecible en su desarrollo.'),
    (31, 3, 5, 'Absolutamente adictivo, ¡no podía dejar de leer!'),
    (32, 4, 4, 'Romántico y con giros inesperados, una lectura muy satisfactoria.'),
    (33, 5, 5, 'Una aventura épica que te lleva a lugares inimaginables.'),
    (34, 6, 4, 'Intrigante y bien construido, me mantuvo interesado en cada capítulo.'),
    (35, 7, 3, 'Interesante pero un poco irregular en su ritmo.'),
    (36, 8, 5, 'Un clásico que merece ser leído una y otra vez.'),
    (37, 9, 4, 'Emocionante y lleno de sorpresas, ¡no pude soltarlo!'),
    (38, 10, 4, 'Fantástico y lleno de imaginación, me transportó a otro mundo.'),
    (39, 11, 5, 'Una joya literaria, cada página es una obra de arte.'),
    (40, 12, 3, 'Entretenido pero con algunos clichés del género.'),
    (41, 13, 5, 'Absolutamente brillante, ¡el autor ha superado todas mis expectativas!'),
    (42, 14, 4, 'Romántico y conmovedor, perfecto para una tarde lluviosa.'),
    (43, 15, 5, 'Una aventura que te mantiene en vilo hasta la última página.'),
    (44, 16, 4, 'Intrigante y bien escrito, me dejó pensando mucho después de terminarlo.'),
    (45, 17, 3, 'Interesante pero un poco predecible en su desarrollo.'),
    (46, 18, 5, 'Una obra maestra del género, ¡no puedo esperar para leer más del autor!'),
    (47, 19, 4, 'Conmovedor y bien escrito, me hizo reflexionar sobre la vida y el amor.'),
    (48, 20, 4, 'Fantástico y lleno de magia, una lectura que recordaré por mucho tiempo.'),
    (49, 21, 5, 'Una historia emocionante que te atrapa desde la primera página.'),
    (50, 22, 3, 'Interesante pero con algunos personajes poco desarrollados.');
